### PR TITLE
Fix Push Notification Issues

### LINKED ISSUE #405: Push Notifications - The 'please subscribe' pop-up appears everytime I refresh, even if I 'Subscribe'

### PR DESCRIPTION
**Pull request by Shailesh351**
Closes https://github.com/WideChat/Rocket.Chat/issues/405 https://github.com/WideChat/Rocket.Chat/issues/403

- [x] Uses the same logic as RC core for desktop notifications(icons, notification click actions etc)
- [x] Earlier even if user disables desktop/mobile notification from the room notification preference, it was sending push notification to all the push subscriptions. So to fix that we are not also adding `platform(desktop or mobile)` along with subscription to only send notification to that platform based on preference.
- [x] Handles mobile push notification. If user has already opened app, instead of reloading again, it will focus the tab.
~~- [x] Removed "Please subscribe to push notifications to continue" popup, which was being shown every time~~

### CODE REVIEW

File: app/lib/server/functions/notifications/mobile.js [hunk 1]
```diff
@@ -68,55 +68,88 @@ export async function getPushData({ room, message, userId, senderUsername, sende
...
+	};
+}
+
+export function sendWebPush(notification, platform) {
 	const gcmKey = settings.get('Push_gcm_api_key');
 	const vapidPublic = settings.get('Vapid_public_key');
 	const vapidPrivate = settings.get('Vapid_private_key');
 	const vapidSubject = settings.get('Vapid_subject');
 
+	if (!gcmKey || !vapidPublic || !vapidPrivate || !vapidSubject) {
```
Comment (bhardwajaditya) [inline app/lib/server/functions/notifications/mobile.js:116]: This check is not required on the server side, instead it should be on the client side. If the application key and project number is missing the user won't be subscribed in the first place.

File: app/lib/server/functions/notifications/mobile.js [hunk 2]
```diff
@@ -68,55 +68,88 @@ export async function getPushData({ room, message, userId, senderUsername, sende
...
+		console.log('Push not configured properly');
```
Comment (bhardwajaditya) [inline app/lib/server/functions/notifications/mobile.js]: Don't console.log in the server

File: app/lib/server/functions/notifications/mobile.js [hunk 3]
```diff
@@ -68,55 +68,88 @@ export async function getPushData({ room, message, userId, senderUsername, sende
...
-		senderUsername,
-		senderName,
-		redirectURL,
-		vibrate: [100, 50, 100],
-		icon: '/images/icons/icon-72x72.png',
-	};
+	if (platform === 'mobile') {
+		notification.platform = platform;
+		notification.vibrate = [100, 50, 100];
+		notification.icon = '/images/icons/icon-96x96.png';
```
Comment (bhardwajaditya) [inline app/lib/server/functions/notifications/mobile.js:147]: Icon is required for desktop as well.

File: client/importServiceWorker.js [hunk 4]
```diff
@@ -59,21 +75,15 @@ Meteor.startup(() => {
 							if (sub === null) {
 								console.log('Not subscribed to push service!');
 								if (settingsReady) {
-									modal.open({
```
Comment (bhardwajaditya) [inline client/importServiceWorker.js]: This modal is required, we cannot directly show the browser notification permission dialog as if it's rejected many times it gives a negative rating to the website in the chrome internal analysis. Please add this preliminary check

File: client/importServiceWorker.js [hunk 5]
```diff
@@ -59,21 +75,15 @@ Meteor.startup(() => {
...
-										title: t('Important'),
-										type: 'info',
-										text: t('Please subscribe to push notifications to continue'),
-										showCancelButton: true,
-										confirmButtonText: t('Subscribe'),
-										cancelButtonText: t('Cancel'),
-										closeOnConfirm: true,
-									}, () => {
-										Notification.requestPermission().then(function(permission) {
+									if (window.Notification && Notification.permission === 'granted') {
```
Comment (bhardwajaditya) [inline client/importServiceWorker.js]: If the permission is granted why to call this method again? We need to subscribe just once

File: public/sw.js [hunk 6]
```diff
@@ -126,33 +126,86 @@ self.addEventListener('fetch', (event) => {
...
-	};
-
-	event.waitUntil(self.registration.showNotification(data.title, options));
+	self.clients.matchAll().then((clients) => {
+		const data = JSON.parse(event.data.text());
+		if (clients && clients.length && data.platform !== 'mobile') {
+			const client = clients[0];
+			client.postMessage(data);
+		} else {
+			const data = JSON.parse(event.data.text());
```
Comment (bhardwajaditya) [inline public/sw.js]: We don't need to declare it again, it's already there in line 156

File: client/importServiceWorker.js [hunk 7]
```diff
@@ -59,21 +75,15 @@ Meteor.startup(() => {
 							if (sub === null) {
 								console.log('Not subscribed to push service!');
 								if (settingsReady) {
```
Comment (bhardwajaditya) [inline client/importServiceWorker.js]: Add a check here for push enabled, if it's allowed, retain the same flow with modal.

File: app/lib/server/functions/notifications/mobile.js (hunk 1 above)
Comment (Shailesh351) [reply app/lib/server/functions/notifications/mobile.js:116]: While sending push notification this block of code is run. As the server is the one sending push, it is required at server side.

> If the application key and project number is missing the user won't be subscribed in the first place.
Even if the if user is not subscribed this block run as we are fetching subscription after this block. https://github.com/WideChat/Rocket.Chat/pull/407/files/1d0296809a6f2ca6dfb20fd0e978a49c7fc2916a#diff-01d45d3cbc3efffd9559d8362662f1a0R125

Let me know if I missed something

File: app/lib/server/functions/notifications/mobile.js (hunk 2 above)
Comment (Shailesh351) [reply app/lib/server/functions/notifications/mobile.js]: Done ✅

File: app/lib/server/functions/notifications/mobile.js (hunk 3 above)
Comment (Shailesh351) [reply app/lib/server/functions/notifications/mobile.js:147]: Yes for the desktop it is already there which is handled by default RC notification as earlier. As for mobile it only supports mono chrome icons, we are overriding with viasat icon.

File: public/sw.js (hunk 6 above)
Comment (Shailesh351) [reply public/sw.js]: Done ✅ Thanks

File: app/lib/server/functions/notifications/mobile.js (hunk 1 above)
Comment (Shailesh351) [reply app/lib/server/functions/notifications/mobile.js:116]: For me server crashed when push was not configured. That's why I have added this check

File: client/importServiceWorker.js (hunk 7 above)
Comment (Shailesh351) [reply client/importServiceWorker.js]: Done ✅

File: client/importServiceWorker.js (hunk 5 above)
Comment (Shailesh351) [reply client/importServiceWorker.js]: User can manually allow/block notifications, in this case subscription is reset and becomes null. So if user manually grants permission then we don't need to again ask for consent. This basically handles this particular case.

File: client/importServiceWorker.js (hunk 4 above)
Comment (Shailesh351) [reply client/importServiceWorker.js]: @bhardwajaditya @ear-dev If we need this modal anyhow, then can we do something like this top banner?
Because showing modal blocking whole screen doesn't look good in UX perspective.
let me know your thoughts

localhost_3000_home(Pixel 2)

File: client/importServiceWorker.js (hunk 5 above)
Comment (bhardwajaditya) [reply client/importServiceWorker.js]: No, basically we need to ask for permission each time, that's the flow we have to follow. If user has manually reset the permission from chrome settings or cleared the site data, we need to again ask for permission. That is in push recommendations. So please follow the previous process.

File: client/importServiceWorker.js (hunk 4 above)
Comment (bhardwajaditya) [reply client/importServiceWorker.js]: What we planned initially was push notifications won't be optional for users it's required for PWA. Being a chat application notifications plays an important part.  Even on android apps we get so many modals at startup asking for basic permissions, that UX was following the similar pattern. If we do this top banner only half the PWA users will opt for notifications and that will degrade the overall chat experience

**Comment by Shailesh351** [comment]
> Aditya: What we planned initially was push notifications won't be optional for users it's required for PWA. Being a chat application notifications plays an important part. Even on android apps we get so many modals at startup asking for basic permissions, that UX was following the similar pattern. If we do this top banner only half the PWA users will opt for notifications and that will degrade the overall chat experience

Let's go ahead with this for now. I have re-added modal. We can revisit it after some feedback or something

File: client/importServiceWorker.js (hunk 4 above)
Comment (Shailesh351) [reply client/importServiceWorker.js]: I have re-added the modal 👍

**Comment by bhardwajaditya** [comment]
> > Aditya: What we planned initially was push notifications won't be optional for users it's required for PWA. Being a chat application notifications plays an important part. Even on android apps we get so many modals at startup asking for basic permissions, that UX was following the similar pattern. If we do this top banner only half the PWA users will opt for notifications and that will degrade the overall chat experience
> 
> Let's go ahead with this for now. I have re-added modal. We can revisit it after some feedback or something

@Shailesh351 Yeah sure, we can discuss tomorrow and decide. Thanks

**Review by bhardwajaditya — APPROVED** [review]
