### PR TITLE
[FIX] Fix livechat transcript sender value

### LINKED ISSUE #1369: [BUG] livechat/gettranscript endpoint always returns the 'sender' as 'agent', even when it should be the visitor.
We use the gettranscript endpoint in our workflow to poll RC for visitor transcripts and we attach them to the Salesforce case.  For some reason the sender is always the 'agent' even when the message was from the visitor. 

example response body from a call to this endpoint:

{
        "sender": "agent",
        "message": "",
        "timestamp": "2023-01-08T16:45:26.008Z"
    },
    {
        "sender": "agent",
        "message": "Hi there! I am a virtual assistant, designed to answer questions about your service.",
        "timestamp": "2023-01-08T16:45:26.155Z"
    },
    {
        "sender": "agent",
        "message": "",
        "timestamp": "2023-01-08T16:45:26.269Z"
    },
    {
        "sender": "agent",
        "message": "How can I help you?",
        "timestamp": "2023-01-08T16:45:29.512Z"
    },
    {
        **"sender": "agent",
        "message": "Good morning, my connection is only connected to local network and mot",
        "timestamp": "2023-01-08T16:45:52.923Z"**
    },
    {
        "sender": "agent",
        "message": "",
        "timestamp": "2023-01-08T16:45:53.850Z"
    },
    {
        "sender": "agent",
        "message": "",
        "timestamp": "2023-01-08T16:45:56.392Z"
    },
    {
        "sender": "agent",
        "message": "",
        "timestamp": "2023-01-08T16:45:58.752Z"
    },
    {
        "sender": "agent",
        "message": "I can help you with the following Wi-Fi questions.",
        "timestamp": "2023-01-08T16:46:01.322Z"
    },
    {
        "sender": "agent",
        "message": "",
        "timestamp": "2023-01-08T16:46:01.399Z"
    },
    {
        "sender": "agent",
        "message": "Connecting to Wi-Fi",
        "timestamp": "2023-01-08T16:46:03.781Z"
    },
    {
        "sender": "agent",
        "message": "<a href=\"https://help.viasat.com/s/article/Viasat-WiFi-Gateway-FAQ-s\" target=\"_blank\" ping=\"https://fulfillment-rc.usres.acc.viasat.io/api/v1/ping/link_slug__vwg_connect_to_wifi/vbbzwwju\">Instructions for connecting to your Viasat WiFi </a> ",
        "timestamp": "2023-01-08T16:46:04.207Z"
    },
    {
        "sender": "agent",
        "message": "Was this information helpful?",
        "timestamp": "2023-01-08T16:46:06.651Z"
    },
    {
        "sender": "agent",
        "message": "",
        "timestamp": "2023-01-08T16:46:06.730Z"
    },
    {
        **"sender": "agent",
        "message": "No",
        "timestamp": "2023-01-08T16:46:18.988Z"**
    },
    {
        "sender": "agent",
        "message": "I'm sorry. Would you like to speak to an agent who can help you further? You can also ask another question.",
        "timestamp": "2023-01-08T16:46:19.340Z"
    },
    {
        "sender": "agent",
        "message": "",
        "timestamp": "2023-01-08T16:46:19.456Z"
    },
    {
        **"sender": "agent",
        "message": "Chat with agent",
        "timestamp": "2023-01-08T16:46:24.179Z"**
    },

### PR DESCRIPTION
**Pull request by bhardwajaditya**
Closes: https://github.com/WideChat/Rocket.Chat/issues/1369

### CODE REVIEW

File: apps/meteor/app/livechat/server/lib/Livechat.js [hunk 1]
```diff
@@ -1367,7 +1367,9 @@ export const Livechat = {
 
 		const room = LivechatRooms.findOneById(rid);
 
-		const visitor = LivechatVisitors.getVisitorByToken(token, { fields: { _id: 1, token: 1, language: 1, username: 1, name: 1 } });
+		const visitor = Promise.await(
+			LivechatVisitors.getVisitorByToken(token, { fields: { _id: 1, token: 1, language: 1, username: 1, name: 1 } }),
+		);
```
Comment (ear-dev) [inline apps/meteor/app/livechat/server/lib/Livechat.js:1372]: Is it the case that visitor was not returning quickly enough, and therefore null, and that somehwere else it was defaulting to 'agent'?  Maybe in Messages.createTranscriptHistoryWithRoomIdMessageAndUser?

Comment (bhardwajaditya) [reply apps/meteor/app/livechat/server/lib/Livechat.js:1372]: @ear-dev it is a synchronous method and this line returns a promise so in this function only at the line it was matching message id with the visitor id and assigning customer or sender based on that. Since promise was not resolved the visitor id was null and it always resolved to agent

**Review by ear-dev — APPROVED** [review]
looks good.
