### PR TITLE
Fix quote message redirection

### LINKED ISSUE #178: Clicking on quote messages redirects to browser view in installed pwa

### PR DESCRIPTION
**Pull request by shubhsherl**
/Closes #178

### CODE REVIEW

**Comment by ear-dev** [comment]
@shubhsherl I'm not sure how to reproduce the original issue being fixed here.  Can you show me the bad behavior?  Thanks.

**Comment by shubhsherl** [comment]
@ear-dev 
output

**Comment by ear-dev** [comment]
What is it that you are clicking here?  Sorry, I can't see your cursor.

**Comment by shubhsherl** [comment]
@ear-dev Quote a message and then click on the time of the quoted msg(to jump to that msg). In mobile, it is opening a web browser, instead of showing quoted msg within installed app. 
Let me know if you are able to reproduce it.

**Comment by ear-dev** [comment]
I was able to reproduce, thanks..  

But in your PR clicking the quoted message opens a DM with the user who originally sent the message.  What is the expected behavior?  Should it scroll to the original message where the quote came from?

**Comment by shubhsherl** [comment]
@ear-dev 
> Should it scroll to the original message where the quote came from?

Yes, it should scroll to original msg.

output
it's working on my device :confused:

**Comment by ear-dev** [comment]
@shubhsherl it is also working for me in the General room, but not when I test it in a DM.  Can you try that as well please?

I'm also having a strange issue where I can't even create a 'quoted' message in my emulator.  Is that working for you?

File: app/ui/client/views/app/room.js [hunk 1]
```diff
@@ -878,11 +878,13 @@ Template.room.events({
...
 	},
-	'click .time a'(e) {
+	'click .time-link'(e) {
 		e.preventDefault();
 		const { msg } = messageArgs(this);
-		const repliedMessageId = msg.attachments[0].message_link.split('?msg=')[1];
-		FlowRouter.go(FlowRouter.current().context.pathname, null, { msg: repliedMessageId, hash: Random.id() });
+		const link = msg.attachments ? msg.attachments[0].message_link : this.message_link;
+		const repliedMessageId = link.split('?msg=')[1];
+		const pathname = `/${ link.split('?msg=')[0].split('/').slice(-2)[0] }/${ link.split('?msg=')[0].split('/').slice(-1)[0] }`;
```
Comment (ear-dev) [inline app/ui/client/views/app/room.js]: Is this string parsing the best way to do it?  Seems like it could be problematic, and it's not very transparent.  @Shailesh351 what do you think of this? Do you mind doing a code review of this PR for me please?

Comment (Shailesh351) [reply app/ui/client/views/app/room.js]: @shubhsherl @ear-dev  We can use 
`const { pathname } = new URL(link);`

**Comment by shubhsherl** [comment]
> @shubhsherl it is also working for me in the General room, but not when I test it in a DM. Can you try that as well, please?

It's working in a DM.

> I'm also having a strange issue where I can't even create a 'quoted' message in my emulator. Is that working for you?

I have not encountered any situation like that.

**Comment by ear-dev** [comment]
Looks good.  Thanks!
