### PR TITLE
[FIX] Typing indicator user avatar fix

### LINKED ISSUE #1330: [BUG][Livechat Widget] Avatar not showing up proper in the widget when SF liveagent is typing
When Salesforce liveagent is typing, an avatar is not the agent name initial, it’s the RC liveagent user avatar

Screenshot 2022-10-20 at 7 05 14 PM

### PR DESCRIPTION
**Pull request by bhardwajaditya**
Closes: https://github.com/WideChat/Rocket.Chat/issues/1330

### CODE REVIEW

File: packages/livechat/src/lib/room.js [hunk 1]
```diff
@@ -293,7 +293,7 @@ Livechat.onTyping((username, isTyping) => {
 	}
 
 	if (typing.indexOf(username) === -1 && isTyping) {
-		typing.push(username);
+		typing.push(agent.name || username);
```
Comment (ear-dev) [inline packages/livechat/src/lib/room.js:296]: oh.... good catch!

**Review by ear-dev — APPROVED** [review]
