### PR TITLE
Fix message retain issue

### LINKED ISSUE #195: Needing to refresh in order to see new messages
In the past couple weeks or so, I can see in the expanded view that I have new messages and can see the one line of new message under the room name in the list view as expected. But then when I go to the room that the new messages are supposed to be in they are not there. I then have to refresh the browser, sometimes multiple times, for the new ones to show up.

### PR DESCRIPTION
**Pull request by shubhsherl**
Closes #195

### CODE REVIEW

**Comment by Shailesh351** [comment]
@shubhsherl Still sometimes it is not showing new messages. and also if chat is open and new msg arrives , it shows unread msg. After that if you refresh page. that msg is gone. Can you check it from your end? Thanks 😄

**Comment by shubhsherl** [comment]
> @shubhsherl Still sometimes it is not showing new messages. and also if chat is open and new msg arrives , it shows unread msg. After that if you refresh page. that msg is gone. Can you check it from your end? Thanks smile

If you refresh the page immediately after a new message, it will disappear after the refresh(as the message is not yet updated in indexedDB) but will appear just after the latest fetch.
Can you check if this is happening or you still need to refresh once or twice for the latest message?

**Comment by Shailesh351** [comment]
@shubhsherl Now we can see new msgs without refreshing. So it does fix issue. Thank you 😄.

One other bug I saw is, if chat is open and new msg arrives , it shows unread msg. After that if you refresh page, it shows 'error-message-ts-out-of-sync' for only one user, doing same for other is not showing error. Can you reproduce the same?

**Review by Shailesh351 — APPROVED** [review]
LGTM

File: app/models/client/models/ChatMessage.js [hunk 1]
```diff
@@ -91,6 +94,8 @@ const messagePreFetch = () => {
 		if (!messagesFetched && CachedChatSubscription.ready.get()) {
 			const status = Meteor.status();
 			if (status.status !== 'connected') {
+				clearTimeout(timeout);
```
Comment (shubhsherl) [inline app/models/client/models/ChatMessage.js:97]: @Shailesh351 a small change here. Sometimes when you refresh, the status shows offline, and then online after some time, and `clearTimeout` is called twice. To avoid that timeout is used.

**Review by Shailesh351 — APPROVED** [review]
