### PR TITLE
Fix SW for API calls by responding with network response first

### LINKED ISSUE #412: Omnichannel Settings not updating instantly after change
Because service worker first respond with cached response, and updates data from server, when user modifies setting it is not reflecting till user hard refresh

### PR DESCRIPTION
**Pull request by Shailesh351**
Closes https://github.com/WideChat/Rocket.Chat/issues/412

### CODE REVIEW

File: public/sw.js [hunk 1]
```diff
@@ -56,17 +56,23 @@ const fetchFromNetwork = (event) => {
...
-		// Only for sockjs
-		return new Response('No connection to the server', {
-			status: 503,
-			statusText: 'No connection to the server',
-			headers: new Headers({ 'Content-Type': 'text/plain' }),
-		});
-	});
+	}).catch(() =>
+		new Promise(function(resolve) {
+			caches.match(event.request.url).then((cached) => {
```
Comment (shubhsherl) [inline public/sw.js]: @Shailesh351 We are already checking cache in previous function, maybe use that to avoid another call.

Comment (Shailesh351) [reply public/sw.js]: Thanks @shubhsherl 🙌  This is actually better way 🥂

**Comment by ear-dev** [comment]
@bhardwajaditya or @shubhsherl if you get a minute can one of you review this please?  If it looks good, should we make sure it is included in the upstream PRs?

sorry.....  I see that Shubham has already taken a look....  thanks!

**Review by shubhsherl — APPROVED** [review]
