### PR TITLE
[Upstream PWA] Some minor fixes

### LINKED ISSUE #276: [Upstream Demo] Fix Sidebar Item UI for ViewMode - Medium, Condensed
socialprototype viasatconnect com_home(Pixel 2 XL) (1)
socialprototype viasatconnect com_home(Pixel 2 XL)

### PR DESCRIPTION
**Pull request by shubhsherl**
Closes #276 #277 #278

### CODE REVIEW

File: app/ui-sidenav/client/sidebarItem.js [hunk 1]
```diff
@@ -169,26 +175,29 @@ Template.sidebarItem.onCreated(function() {
 			}
 		}
 
-		if (!currentData.lastMessage._id) {
+		if (currentData.lastMessage && !currentData.lastMessage._id) {
```
Comment (Shailesh351) [inline app/ui-sidenav/client/sidebarItem.js:178]: @shubhsherl  Instead of checking for `currentData.lastMessage &&` in every if conditions, can we add one if block above?
```
if(!currentData.lastMessage){
    return;
}
```

**Comment by Shailesh351** [comment]
Following changes from this PR are added in Upstream PR #17375

- [x] Directly open main content when url is not `'/', '/home', '/account'`
- [x] Set View Mode default to extended and hide View Mode from Menu
- [x] Last Message Delivery Indicator(check and clock icon)
